### ISSUE TITLE
Iugu não aparece como meio de pagamento

### ISSUE THREAD

**Issue by yuriwally** [iugu/iugu-magento-2#1]
Configurei o módulo conforme documentação, mas o mesmo não aparece como meio de pagamento.

![image](https://user-images.githubusercontent.com/36455/95346131-e1698080-0891-11eb-95c1-0d591f415107.png)

O plugin está instalado e configurado para testes:

![image](https://user-images.githubusercontent.com/36455/95343910-6c954700-088f-11eb-9037-9523c941a3e0.png)

![image](https://user-images.githubusercontent.com/36455/95344233-ceee4780-088f-11eb-898a-0acd5271c400.png)

Nosso composer.json é o seguinte:

```
{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    },
    "require": {
        "magento/product-community-edition": "2.3.3",
        "magento2translations/language_pt_br": "dev-master",
        "smile/module-map": "^2.0",
        "smile/module-retailer": "1.2.9.1",
        "smile/module-seller": "^1.2",
        "smile/module-store-delivery": "^1.1",
        "smile/module-store-locator": "^2.0"
    },
    "require-dev": {
        "allure-framework/allure-phpunit": "~1.2.0",
        "friendsofphp/php-cs-fixer": "~2.14.0",
        "lusitanian/oauth": "~0.8.10",
        "magento/magento-coding-standard": "~3.0.0",
        "magento/magento2-functional-testing-framework": "2.4.5",
        "pdepend/pdepend": "2.5.2",
        "phpmd/phpmd": "@stable",
        "phpunit/phpunit": "~6.5.0",
        "sebastian/phpcpd": "~3.0.0",
        "squizlabs/php_codesniffer": "~3.4.0"
    },
    "conflict": {
        "gene/bluefoot": "*"
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/",
            "Zend\\Mvc\\Controller\\": "setup/src/Zend/Mvc/Controller/"
        },
        "psr-0": {
            "": [
                "app/code/",
                "generated/code/"
            ]
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ],
        "exclude-from-classmap": [
            "**/dev/**",
            "**/update/**",
            "**/Test/**"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/"
        }
    },
    "version": "2.3.3",
    "minimum-stability": "stable",
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],
    "extra": {
        "magento-force": "override"
    }
}
```

Não aparece nenhuma exception nem erro nos logs também.

**Comment by ianitsky** [comment]
Talvez seja problema de cache do Javascript ou compilação dos arquivos do magento.

tente rodar os seguintes comandos:

 bin/magento setup:upgrade && bin/magento setup:di:compile && bin/magento cache:clean && bin/magento setup:static-content:deploy

Pergunta. Estão usando algum módulo de checkout customizado?

**Comment by yuriwally** [comment]
Comandos executados, mesmo cenário.

Estamos usando um plugin de entrega em loja ( https://github.com/Smile-SA/magento2-module-store-delivery ) e um tema.

**Comment by ianitsky** [comment]
Testamos o checkout com o tema mencionado e o erro não pudemos reproduzir o problema.
Provavelmente seja algum erro de configuração.

**Comment by yuriwally** [comment]
Não parece ser problema de configuração, só consegui fazer funcionar ao comentar algumas linhas:

linha 8:
`https://app.sistemaindustria.com.br/ERPBarramento`

linha 30:
`coupon,`

linha 98:
`coupon.isApplied.subscribe(this.reupdateInstallments, this);`

o magento 2.3 ultima versão não possui o arquivo _coupon.js_.

**Comment by ianitsky** [comment]
@yuriwally 

Talvez o módulo SalesRules do seu magento não esteja habilitado, ou sua instalação não esteja completa.

A versão 2.3 tem sim o coupon: https://github.com/magento/magento2/blob/2.3/app/code/Magento/SalesRule/view/frontend/web/js/model/coupon.js

E essa linha 8 "https://app.sistemaindustria.com.br/ERPBarramento" eu desconheço;
