### ISSUE TITLE
Erro getIuguCustomerId()

### ISSUE THREAD

**Issue by fastcom2015** [iugu/iugu-magento-2#2]
Olá pessoal, 
Utilizo Magento versão 2.3.6
Versão PHP 7.2
Link https://magento.fastcom.dev/

Estou recebendo o erro abaixo ao tentar concluir uma compra, verifiquei que a função getIuguCustomerI  não existe dentro do diretório Iugu\\Payment\\Helper\\IuguHelpe, alguém poderia me ajudar. 

PHP Fatal error:  Uncaught Error: Call to undefined method Iugu\\Payment\\Helper\\IuguHelper::getIuguCustomerId() in /home/fastcomdev/domains/magento.fastcom.dev/public_html/app/code/Iugu/Payment/Gateway/Request/PayerDataBuilder.php:135, referer: https://magento.fastcom.dev/checkout/

Att;

**Comment by ianitsky** [comment]
Vou verificar esse problema e retorno com uma mensagem ou um deploy.

**Comment by ianitsky** [comment]
@fastcom2015 Por algum motivo nem todos os arquivos tinham entrado no commit.

Por favor, baixe a nova versão e retorne aqui para dizer se está funcionando ok para vocês.

Você pode testar essa versão no seguinte endereço:  https://34.220.169.58/index.php

**Comment by fastcom2015** [comment]
Bom dia @ianitsky.
Obrigado, vamos atualizar os arquivos.

**Comment by ianitsky** [comment]
Estou fechando esta issue por falta de atualização.
Qualquer comentário sobre o mesmo problema só reabrir.
